### PR TITLE
deployed the repo to heroku + add the live demo to README.md file

### PR DESCRIPTION
**Pull request by dasileker**
### Heroku deploy

1. add the repo Ror-social-scaffold to the Heroku.
2.  add the live demo link to the README.md file

### CODE REVIEW

**Review by LamiaSristy — COMMENTED** [review]
# Invalid CRR
# You haven't applied linters in your branch. ✖️ 

# You should have merged a PR from the development branch to the main/master branch with all changes made by them in previous milestones

Feel free to reach me at @lamiasristy 🙋

**Comment by dasileker** [comment]
i don't understand should I do the comparing between the branch and the development or tge master, I'm confused now

**Comment by dasileker** [comment]
okay I fixed the linters, it was disabled on the Github settings

**Review by oloomoses — APPROVED** [review]
# Congratulation! Project Approved :tada: :muscle: :clap: 
### Greate Job team
#### You can now merge and close this pull request.
### I wish you the very best in your next project

**Pull request merged**
