### PR TITLE
Friednship-v1

### PR DESCRIPTION
**Pull request by dasileker**
### In this  branch :

1.created the friendship model and controller
2. add the friendship request & accept & reject
3. add the gems gravatar_imag_tag &  factory_bot_rails & rails_controller_testing
4. add the gem for the test ' faker & launchy & 

> I added the  test like supposed to it contains 53 tests

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Comment by dasileker** [comment]
> # This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
> ## Please wait a bit ...

where is the review?

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
Hello @dasileker  :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this milestone. However your code review request is marked as invalid due to the following reasons:

1. The submitted Pull Request contain is violating the correct git/github flow it should be from feature branch to develop branch, not feature to master branch

_`Action to be taken:` While you are preparing for the other code review request submission, we need you to submit an open Pull Request which is referring from feature branch to develop branch, and it needs to be open => (not merged and not closed)_

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
.

**Comment by dasileker** [comment]
okay thank you, but can you please mark the project in the dashboard to have another review.

**Review by NtwaliHeritier — APPROVED** [review]
### STATUS: APPROVED✔

Hello Team,
Great work on this milestone. It's looking good and working like a charm.
[OPTIONAL]: Add a notification tab at the top, to see the list of request, instead of having to go  to all users.

**Pull request merged**
