### PR TITLE
Friendship v2

### PR DESCRIPTION
**Pull request by dasileker**
### Friendship v2 with implemented  friendship with 2 rows

1. refactored the (friendship. rb) to take two rows of mutual friendship.
2. add style to the costume.css for the buttons add friend & cancel the request.
3. test RSpec is already implemented in the previous branch.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [x] Please add linters.
- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created

```

# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

- [x] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
```

- [x]  in order to get all posts written by a user on their friends, students can use the simple method in the User model (in order to NOT do it with Enumerable)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by dasileker** [comment]
I do have linters?

**Comment by dasileker** [comment]
ok, all done thank you it's very helpful

**Review by cristianCeamatu — APPROVED** [review]
### 🥇 APPROVED 🥇 

Congratulations and good luck with the next projects!

If you ever need any help or notice that you are wasting too many hours on a bug don't hesitate to contact me on Slack.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Comment by dasileker** [comment]
> ### 🥇 APPROVED 🥇 
> 
> Congratulations and good luck with the next projects!
> 
> If you ever need any help or notice that you are wasting too many hours on a bug don't hesitate to contact me on Slack.
> 
> Best regards,
> Cristian Ceamatu
> Slack: Cristian Viorel Ceamatu

if i have any issues i will, thanks Christian for the previous help and the upcoming ones.

**Comment by arslanbisharat** [comment]
> I do have linters?

@dasileker I can see you added files but linters are not working.

**Pull request merged**
